name: teststandgui

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pip
  - pip:
      - PyQt6
      - protobuf
      - grpcio
      - grpcio-tools
      - opencv-python
